Changes to Smartlink201/BLExtender Initial to use JLink (fix issues).
Fix: TypeError: __init__() missing 1 required positional argument:
'sw_nrf_projectfile'